### ISSUE TITLE
Bug?: mutable value

### ISSUE THREAD

**Issue by disconnect3d** [disconnect3d/cint#3]
TLDR:
```
In [1]: import cint

In [2]: x = cint.I8(127)

In [3]: y = x

In [4]: y += 1

In [5]: y, x
Out[5]: (I8(-128), I8(-128))
```
while this is correct for Python -  `x` and `y` are the same objects, it is not that intuitive for C-like code.

What I mean is, a similar syntax in C will do sth  different:
```c
int8_t x = 127;
int8_t y = x;
y+= 1;
// x is 127
// y is -128
```
the results are different.

The question is: how should it be handled?

**Comment by disconnect3d** [comment]
One of the solutions: leave it as it is.

Another solution: make it more c-like, as in:
```
In [17]: class A:
    ...:     def __init__(self, x):
    ...:         self.x = x
    ...:
    ...:     def __iadd__(self, o):
    ...:         return A(self.x + o)
    ...:

In [18]: a = A(5)

In [19]: b = a

In [20]: a.x, b.x
Out[20]: (5, 5)

In [21]: a += 2

In [22]: a.x, b.x
Out[22]: (7, 5)

In [23]: b += 3

In [24]: a.x, b.x
Out[24]: (7, 8)
```

**Comment by gbdlin** [comment]
This is not intuitive in Python, because integers are not mutable in Python. Each operation creates a new object and IMO cint should behave the same. You cannot fully introduce C integers in Python, because everything is passed as a reference in Python, it is not copied. Only way to emulate that behavior is to make cint fully immutable.
